version: '3'
services:
  dose:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - magnet
    links:
      - magnet

  magnet:
    build: ./mujin-magnet
    ports:
      - 5003:5000
    volumes:
      - ./mujin-magnet:/app
    devices:
      - /dev/gpiomem:/dev/gpiomem
